spring:
  data:
    mongodb:
      host: statistics-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: statistics-service
          client-secret: ${STATISTICS_SERVICE_PASSWORD}
      client:
        registration:
          statistics-service:
            client-id: statistics-service
            client-secret: ${STATISTICS_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
        provider:
          statistics-service:
            token-uri: http://auth-service:5000/uaa/oauth2/token

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io
